# Generated by Django 4.2.14 on 2024-07-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
