# Generated by Django 4.2.14 on 2024-07-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_contactquery_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactquery',
            name='phone_number',
        ),
    ]
