# Generated by Django 4.2.14 on 2024-07-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_contactquery_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
